
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app 
        image: nikhilnambiars/flask-app:flask-app-docker-image
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred    

---

apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer
